Update patch set 6
Patch Set 6:

> Patch Set 6:
> 
> Can you pls try to change to http://trex-tgn.cisco.com/trex/release/ (instead of https) and see if it works better?

We have the same behaviour when building docker image.
See error:
ERROR: cannot verify trex-tgn.cisco.com's certificate, issued by 'CN=HydrantID SSL ICA G2,O=HydrantID (Avalanche Cloud Corporation),C=US':
  Unable to locally verify the issuer's authority.
To connect to trex-tgn.cisco.com insecurely, use `--no-check-certificate'.

HTTP URL does not exists

Can you check with TRex team ? Or maybe we can use Github url instead of Cisco ones ?

Patch-set: 6
Label: Verified=0